### ISSUE TITLE
bug: Some invalid queries get exposed as "unknown" or "Intenal" instead of "ValidationError" or "BadRequest" in micrometer

### ISSUE THREAD

**Issue by hpuac** [Netflix/dgs-framework#1058]
## Expected behavior

When modifying the GraphQL request and sending a variable that is not in the query, I would expect it to get exposed as `ValidationError` or `BAD_REQUEST` in micrometer.

## Actual behavior

- When modifying the GraphQL request and sending a variable that is not in the query, it gets exposed as errorType `unknown` in micrometer. 
- When modifying a federated GraphQL request and sending a variable that is not in the query, it gets exposed as errorTyoe `INTERNAL` in micrometer.

This is preventing me to exclude client errors from our alerting that we base on these metrics.

## Steps to reproduce

I think the behaviour description is pretty self explanatory. Please let me know if something is not clear.
But I'd like to provide some additional information.
- When the error type "unknown" is exposed, the exception that `DgsGraphQLMetricsInstrumentation->instrumentExecutionResult` receives is `graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name 'myDemoKey' that is not defined for input object type 'MyDemoInput' `. The `ErrorUtils.sanitizeErrorPaths()` call then sets the type to `unknown`.
- When the error type `INTERNAL` is exposed,  the exception that `DgsGraphQLMetricsInstrumentation->instrumentExecutionResult` receives is `TypedGraphQLError{message='java.lang.IllegalStateException: Expected key 'myDemoKey' in received federated values map does not exist.', locations=[], path=[_entities], extensions={errorType=INTERNAL}}`. The `ErrorUtils.sanitizeErrorPaths()` call then sets the type to `INTERNAL`.

**Comment by berngp** [comment]
Thanks @hpuac, it should be consistent with `BAD_REQUEST` in both cases.

**Comment by srinivasankavitha** [comment]
Closing this issue since it should be addressed in the latest release. Please reopen, if issue exists.

**Comment by hpuac** [comment]
Hey @srinivasankavitha, sorry for the delay but I was now able to re-test it with DGS 5.0.5.
The following errors are still not exposed to micrometer as expected:
- Exposed as `INTERNAL`: `{"message":"com.netflix.graphql.dgs.exceptions.MissingFederatedQueryArgument: The federated query is missing field(s) __typename","locations":[],"path":["_entities"],"extensions":{"errorType"
:"INTERNAL"}}`
- Exposed as `unknown`: `{"message":"Variable 'representations' has an invalid value: Variable 'representations' has coerced Null value for NonNull type '[_Any!]!'","locations":[{"line":1,"column":23}],"extensions":{
"classification":"ValidationError"}}`
- Exposed as `unknown`: `{"message":"Variable 'input' has an invalid value: Variable 'input' has coerced Null value for NonNull type 'MyDemoInput!'","locations":[{"line":1,"column":36}],"extensions":{"c
lassification":"ValidationError"}}`
- Exposed as `unknown`: `{"message":"The variables input contains a field name 'myDemoName' that is not defined for input object type 'MyDemoInput' ","extensions":{"classification":"ValidationError"}}`
- Does not get exposed to micrometer as error at all: `{"message":"The query is null or empty.","locations":[],"extensions":{"errorType":"BAD_REQUEST"}}`

**Comment by hpuac** [comment]
Hey @berngp and @srinivasankavitha, should I create a new issue or will you reopen this one? 🙂

**Comment by berngp** [comment]
Let's keep this one.

**Comment by hpuac** [comment]
@berngp do you have the rights to reopen it? I don't have any button for it.
