### ISSUE TITLE
bug: Issues deserializing complex input objects in 4.7.3

### ISSUE THREAD

**Issue by nsnichols** [Netflix/dgs-framework#607]
I'm seeing a couple different issues deserializing input objects after upgrading to 4.7.3.

1. If you have a list of enums in an input field, those enum objects are not deserialized into instances of the enum. They are left as strings.
2. If you have an object that you are attempting to deserialize into that has fields that are in a superclass instead of directly on the target class, an exception is thrown while deserializing the input claiming that the field does not exist.

## Expected behavior

Input values are correctly deserialized into the appropriate java types.

## Actual behavior

Enums are left as strings (when in a List). It is impossible to deserialize into fields that are on parent classes of the target class.

## Steps to reproduce

Here's a simple test case for the enum deserialization issue:

```
type Query {
    withInputContainingEnumList(input: Input!): Output!
}

input Input {
    values: [SomeEnum!]!
}

type Output {
    values: [SomeEnum!]!
}

enum SomeEnum {
    ONE, TWO
}
```
```
    @DgsComponent
    public class Fetcher {
        @DgsQuery(field = DgsConstants.QUERY.WithInputContainingEnumList)
        public Output doQuery(@InputArgument("input") Input input) {
            // Blows up on the next line. The value is still a string, not an enum instance.
            var enumValue = input.getValues().get(0);
            return Output.newBuilder().values(List.of(enumValue)).build();
        }
    }
```

For the second issue, we have type mappings set up to point at a pre-existing class that has its fields defined on an ancestor class.

When the input deserialization logic calls getDeclaredField, an exception is thrown.

```
    @Getter
    @Setter
    public class Parent {
        String someField;
    }

    public class Child extends Parent {

    }
```
```
type Query {    
    withChild(child: ChildInput): ChildOutput
}

input ChildInput {
    someField: String!
}

type ChildOutput {
    someField: String!
}
```
```
// gradle generator config
generateJava {
    // ...
    typeMapping = [
            ChildInput: 'Child',
            ChildOutput: 'Child'
    ]
}
```
```
    @DgsComponent
    public static class Fetcher {
        @DgsQuery(field = DgsConstants.QUERY.WithChild)
        public Child doQuery(@InputArgument("child") Child input) {
            // We never get to this point. An exception is thrown during deserialization
            return null;
        }
    }
```

**Comment by berngp** [comment]
Hi @nsnichols, thanks for reporting the issues.

> 1. If you have a list of enums in an input field, those enum objects are not deserialized into instances of the enum. They are left as strings.

There is already a [PR merged](https://github.com/Netflix/dgs-framework/pull/604) but not yet released. We are aware of the 

> 2. If you have an object that you are attempting to deserialize into that has fields that are in a superclass instead of directly on the target class, an exception is thrown while deserializing the input claiming that the field does not exist.

Looks like this is a duplicate of #584. We are actively working on it and will update this thread as soon as we have a fix.

**Comment by nsnichols** [comment]
@berngp, whoops. Sorry for logging a duplicate issue. I just noticed that it looks like lists of lists don't get deserialized properly on input objects. Is that also reported somewhere else?

**Comment by berngp** [comment]
@nsnichols not at all, on the contrary, you nailed the specifics of both issues. We were struggling to understand the 2nd one until today morning.

**Comment by nsnichols** [comment]
Here's the issue with lists of lists:
```
type Query {
    withListOfLists(listOfLists: ListOfLists!): Output!
}

input ListOfLists {
    lists: [[Nested]]!
}

input Nested {
    field: String!
}
```

```
val newList = convertList(it.value as List<*>, Class.forName(actualType.typeName).kotlin)
```
The line above in the input mapper throws an exception since there is no class named `List<Nested>`. Assuming it got past that line, right now `convertList` will just return the item directly which will cause a different class cast exception when we try to use the value in the list.

**Comment by berngp** [comment]
@nsnichols we just released 4.7.4 with fixes on input argument serialization. Could you please try that version out?

That said, I don't think we have seen nested list in such a way.

**Comment by nsnichols** [comment]
@berngp, I gave 4.7.4 a try. The list of enums issue is definitely fixed. The deserializing into an inherited field issue still exists for me, though the error is different. An index out of bounds exception is now thrown. This is because my parent class is generic. With a small tweak to the Parent/Child classes in my first post, I can trigger the exception with the query from that post.

```
    @Getter
    @Setter
    public class Parent<T> {
        String field;

        T value;
    }

    public class Child extends Parent<Integer> {}
```

Here's the relevant stack trace
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at com.netflix.graphql.dgs.internal.InputObjectMapper.getFieldType(InputObjectMapper.kt:122)
	at com.netflix.graphql.dgs.internal.InputObjectMapper.mapToJavaObject(InputObjectMapper.kt:78)
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.convertValue(DataFetcherInvoker.kt:240)
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.processInputArgument(DataFetcherInvoker.kt:207)
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.invokeDataFetcher(DataFetcherInvoker.kt:62)
```

```
    fun getFieldType(field: Field, genericSuperclass: Type,): Class<*> {
        val type: Type = field.genericType
        return if (type is ParameterizedType) {
            Class.forName(type.actualTypeArguments[0].typeName)
        } else if (genericSuperclass is ParameterizedType) {
            val typeParameters = (genericSuperclass.rawType as Class<*>).typeParameters
            val indexOfTypeParameter = typeParameters.indexOfFirst { it.name == type.typeName }
   // indexOfTypeParameter is -1 here since the type of the field (String) is not found in the class generic types (Integer)
            Class.forName(genericSuperclass.actualTypeArguments[indexOfTypeParameter].typeName)
        } else {
            field.type
        }
    }
```

The list of lists issue is still there too. I don't know how common that scenario is, but it is a valid graphql schema.

**Comment by berngp** [comment]
Thanks @nsnichols, will look into it.

**Comment by paulbakker** [comment]
The generics related issue fixed here: https://github.com/Netflix/dgs-framework/pull/611

**Comment by nsnichols** [comment]
All my tests are green with 4.7.5. Thanks guys.

**Comment by paulbakker** [comment]
Awesome, thanks for confirming so quickly @nsnichols. I think we can close this issue now :)

**Comment by jrogers** [comment]
This seems to still be a problem if the input is a list of enums. The result list still contains strings, ex:
```
query {
  lookup(types: [MyTypeEnum!]): [Result]
}

enum MyTypeEnum {
  TYPE1,
  TYPE2
}
```

This will fail:
```
query TestQuery {
  lookup(types: [TYPE1])
}
```

However if you nest the enum inside another input object the deserialization does work correctly:
```
query {
  lookup(types: MyLookupType): [Result]
}

input MyLookupType {
  types: [MyTypeEnum!]!
}

enum MyTypeEnum {
  TYPE1,
  TYPE2
}
```

this will work:
```
query TestQuery {
  lookup(types: { types: [TYPE1]})
```

**Comment by berngp** [comment]
Thanks for reporting.

**Comment by berngp** [comment]
@jrogers , please followup via https://github.com/Netflix/dgs-framework/issues/644.
